# -*- coding: utf-8 -*-
"""ViT-Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Riqw7DH6z7nk8aBYAhdFt3skJuAcdfQ

Imports
"""

import streamlit as st
import tensorflow as tf
import requests
from PIL import Image

!pip install streamlit

# Title
st.title("Apple Plant Disease Detection")
st.write("Upload an image of the leaf")

# Upload image
uploaded_image = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

# Load the model
# legacy_model = tf.python.keras.models.load_model('vit_al9ee')
# legacy_model.save('vit_al9ee.keras')

model = tf.keras.models.load_model('saved_model')

# Function to predict disease
def predict_disease(input_image):
    predictions = model(input_image)
    return predictions

# Function to get probable cure from ChatGPT API
def get_probable_remedy(disease_name):
    api_key = 'api_key'  # Replace with your any gemini/opem API key
    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json'
    }
    data = {
        "model": "your_model",
        "messages": [
            {"role": "system", "content": "You are an expert in plant diseases."},
            {"role": "user", "content": f"Provide a probable cure in 20-30 words for {disease_name} in apple plants."}
        ],
        "max_tokens": 50
    }
    response = requests.post('https://api.openai.com/v1/chat/completions', headers=headers, json=data)
    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return "Could not retrieve cure information."

# Display uploaded image and predict
if uploaded_image is not None:
    image = Image.open(uploaded_image)
    st.image(image, width=200)

    if st.button("Detect Disease"):
        prediction_result = predict_disease(image)
        st.success(f"Prediction: {prediction_result}")

        # Get probable cure
        cure = get_probable_remedy(prediction_result)
        st.info(f"Probable Cure: {cure}")
