# -*- coding: utf-8 -*-
"""ViT-Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Riqw7DH6z7nk8aBYAhdFt3skJuAcdfQ

Imports
"""

import streamlit as st
import tensorflow as tf
import requests
from PIL import Image

!pip install streamlit

# Title
st.title("Apple Plant Disease Detection")
st.write("Upload an image of the leaf")

# Upload image
uploaded_image = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

# Load the model
# legacy_model = tf.python.keras.models.load_model('vit_al9ee')
# legacy_model.save('vit_al9ee.keras')

model = tf.keras.models.load_model('saved_model')

# Function to predict disease
def predict_disease(input_image):
    predictions = model(input_image)
    return predictions

# Function to get probable cure from ChatGPT API
def get_probable_remedy(disease_name):
    api_key = 'api_key'  # Replace with your any gemini/opem API key
    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json'
    }
    data = {
        "model": "your_model",
        "messages": [
            {"role": "system", "content": "You are an expert in plant diseases."},
            {"role": "user", "content": f"Provide a probable cure in 20-30 words for {disease_name} in apple plants."}
        ],
        "max_tokens": 50
    }
    response = requests.post('https://api.openai.com/v1/chat/completions', headers=headers, json=data)
    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return "Could not retrieve cure information."

# Display uploaded image and predict
if uploaded_image is not None:
    image = Image.open(uploaded_image)
    st.image(image, width=200)

    if st.button("Detect Disease"):
        prediction_result = predict_disease(image)
        st.success(f"Prediction: {prediction_result}")

        # Get probable cure
        cure = get_probable_remedy(prediction_result)
        st.info(f"Probable Cure: {cure}")

import numpy as np
# import tensorflow as tf

loaded_model = tf.keras.models.load_model('/content/drive/MyDrive/Apple_Plant_DD_ViT/vit_al9ee')
loaded_model.summary()

IMG_WIDTH = 120
IMG_HEIGHT = 120
BATCH_SIZE = 100

TESTING_DATASET_DIR = '/content/drive/MyDrive/Apple_Plant_DD_ViT/dataset/Test'
dataset = tf.keras.utils.image_dataset_from_directory(
  TESTING_DATASET_DIR,
  image_size=(IMG_HEIGHT, IMG_WIDTH),
  batch_size=BATCH_SIZE
)

correctly_predicted = 0
total_images = 0
for step, (images, labels) in enumerate(dataset):
  actual_results = labels.numpy()
  predictions = loaded_model(images)
  for j in range(len(predictions.numpy())):
    total_images += 1
    pd = predictions[j]
    max_i = 0
    for i in range(len(pd)):
        if pd[i] > pd[max_i]:
            max_i = i
    if max_i == actual_results[j]:
        correctly_predicted += 1

print(f"accuracy -> {correctly_predicted / total_images}")